#!/bin/bash

synclient LeftEdge 1760
synclient RightEdge 5302
synclient TopEdge 1625
synclient BottomEdge 4291
synclient FingerL 25
synclient FingerHigh 30
synclient MaxTapTime 180
synclient MaxTapMove 226
synclient MaxDoubleTapTime 100
synclient SingleTapTimeout 180
synclient ClickTime 100
synclient EmulateMidButtonTime 75
synclient EmulateTwoFingerMinZ 282
synclient EmulateTwoFingerMinW 7
synclient VertScrollDelta 103
synclient HorizScrollDelta 103
synclient VertEdgeScroll 0
synclient HorizEdgeScroll 0
synclient CornerCoasting 0
synclient VertTwoFingerScroll 1
synclient HorizTwoFingerScroll 1
synclient MinSpeed 1
synclient MaxSpeed 1.75
synclient AccelFactor 0.0388048
synclient TouchpadOff 0
synclient LockedDrags 0
synclient LockedDragTimeout 5000
synclient RTCornerButton 0
synclient RBCornerButton 0
synclient LTCornerButton 0
synclient LBCornerButton 0
synclient TapButton1 1
synclient TapButton2 2
synclient TapButton3 0
synclient ClickFinger1 1
synclient ClickFinger2 1
synclient ClickFinger3 0
synclient CircularScrolling 0
synclient CircScrollDelta 0.1
synclient CircScrollTrigger 0
synclient CircularPad 0
synclient PalmDetect 1
synclient PalmMinWidth 10
synclient PalmMinZ 200
synclient CoastingSpeed 20
synclient CoastingFriction 50
synclient PressureMotionMinZ 30
synclient PressureMotionMaxZ 160
synclient PressureMotionMinFactor 1
synclient PressureMotionMaxFactor 1
synclient ResolutionDetect 1
synclient GrabEventDevice 0
synclient TapAndDragGesture 1
synclient AreaLeftEdge 0
synclient AreaRightEdge 0
synclient AreaTopEdge 0
synclient AreaBottomEdge 0
synclient HorizHysteresis 25
synclient VertHysteresis 25
synclient ClickPad 0
