
set number	" Show line numbers
set linebreak	" Break lines at word (requires Wrap lines)
set showmatch	" Highlight matching brace
set visualbell	" Use visual bell (no beeping)
 
set hlsearch	" Highlight all search results
set smartcase	" Enable smart-case search
set ignorecase	" Always case-insensitive
set incsearch	" Searches for strings incrementally

set autoindent	" Auto-indent new lines
set expandtab	" Use spaces instead of tabs
set shiftwidth=4	" Number of auto-indent spaces
set smartindent	" Enable smart-indent
set smarttab	" Enable smart-tabs
set softtabstop=4	" Number of spaces per Tab
 
" Advanced
set ruler	" Show row and column ruler information

set undolevels=1024	" Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour

" Generated by VimConfig.com (up to this)

set relativenumber " nuber lines relative to current

" change directions for colemak
set langmap=jh,hk,kj

set belloff=cursor " disable bell for movement at line edge

set scrolloff=64 " keep cursor at centre of screen

" set cursorline " highlight current line

autocmd! bufwritepost .vimrc source % " autoreload vimrc

nnoremap <buffer> <F9> :w<cr>:exec '!python3' shellescape(@%, 1)<cr>
" f9 to run py script

set nobackup " disable creating backups
set nowritebackup

" pathogen for managing plugins:
execute pathogen#infect()

" colorscheme
syntax enable
colorscheme solarized
set background=dark
